# Grundregeln für das Projekt
disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - fatal_error_message

# Spezielle Regeln für View-Dateien
type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60

# Ausnahmen
excluded:
  - Pods
  - build
  - .build
  - DerivedData