sonar.projectKey=WEGHausverwaltung
sonar.projectName=WEG Hausverwaltung 2.0
sonar.projectVersion=1.0
sonar.sources=WEG Hausverwaltung 2.0
sonar.sourceEncoding=UTF-8
sonar.language=swift
sonar.swift.project=WEG Hausverwaltung 2.0.xcodeproj
sonar.swift.workspace=WEG Hausverwaltung 2.0.xcworkspace
sonar.host.url=http://localhost:9000